services:
    fun_pro_engine.version_listener:
        class: FunPro\EngineBundle\Listener\FilterControllerByApiVersion
        arguments: ["@router", "%api_current_version%", "%api_available_versions%"]
        tags:
            - { name: kernel.event_subscriber }