services:
    fun_pro_engine.version_listener:
        class: FunPro\EngineBundle\Listener\FilterControllerByApiVersion
        arguments: ["@router", "%api_current_version%", "%api_available_versions%"]
        tags:
            - { name: kernel.event_subscriber }

    security.authentication.success_handler:
        class: FunPro\EngineBundle\Authentication\SuccessHandler
        arguments:  ["@security.http_utils", {}]

    security.authentication.failure_handler:
        class:  FunPro\EngineBundle\Authentication\FailureHandler
        arguments:  ["@http_kernel", "@security.http_utils", {}, "@logger"]

    fun_pro_engine.login_subscriber:
        class: FunPro\EngineBundle\Listener\LoginSubscriber
        arguments: ["@doctrine", %login.max_failure_count%]
        tags:
            - { name: kernel.event_subscriber }

    fun_pro_engine.token_authenticator:
        class: FunPro\EngineBundle\Authentication\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']

    funpro_engine.user_provider.mobile:
        class: FunPro\EngineBundle\Security\TokenUserProvider
        arguments: [@fos_user.user_manager, @doctrine]