services:
    jms_serializer.naming_strategy:
        class: 'JMS\Serializer\Naming\SerializedNameAnnotationStrategy'
        arguments: [@jms_serializer.identical_strategy]

    fun_pro_engine.gcm_collector:
        class: FunPro\EngineBundle\Profiler\GCMDataCollector
        tags:
            - { name: data_collector, id: 'GCM', template: 'FunProEngineBundle:Profiler:template' }
        public: false

    jms_serializer.identical_strategy:
        class: 'JMS\Serializer\Naming\IdenticalPropertyNamingStrategy'

    fun_pro_engine.gcm:
        class: FunPro\EngineBundle\GCM\GCM
        arguments: ["@doctrine", "@serializer", "@logger", "@fun_pro_engine.gcm_collector", "%gcm.api_key%", "%kernel.environment%"]
        tags:
            -
                name: kernel.event_listener
                event: "%gcm.queue.process_in%"
                method: 'processQueue'
                priority: "%gcm.queue.priority%"

    fun_pro_engine.version_listener:
        class: FunPro\EngineBundle\Listener\FilterControllerByApiVersion
        #FIXME: How specify version for passenger & driver
        arguments: ["@router", "%api.passenger.version.current%", "%api.passenger.version.available%"]
        tags:
            - { name: kernel.event_subscriber }

    security.authentication.success_handler:
        class: FunPro\EngineBundle\Authentication\SuccessHandler
        arguments: ["@security.http_utils", {}]

    security.authentication.failure_handler:
        class:  FunPro\EngineBundle\Authentication\FailureHandler
        arguments:  ["@http_kernel", "@security.http_utils", {}, "@logger"]

    fun_pro_engine.login_subscriber:
        class: FunPro\EngineBundle\Listener\LoginSubscriber
        arguments: ["@doctrine", %login.max_failure_count%]
        tags:
            - { name: kernel.event_subscriber }

    fun_pro_engine.user_token_authenticator:
        class: FunPro\EngineBundle\Authentication\UserTokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@logger']

    fun_pro_engine.device_token_authenticator:
        class: FunPro\EngineBundle\Authentication\DeviceTokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']

    fun_pro_engine.device_checker:
        class: FunPro\EngineBundle\EventListener\DeviceListener
        arguments: ["@doctrine", "@security.token_storage", "@logger"]
        tags:
            - { name: kernel.event_subscriber }