FunPro\DriverBundle\Entity\Driver:
    properties:
        name:
            - NotBlank: ~
        email:
            - Email:
                groups: ["Register", "Update"]
        username:
            - NotBlank:
                groups: ['Register']
                message: 'fos_user.username.blank'
            - Length:
                min: 2
                max: 255
                minMessage: 'fos_user.username.short'
                maxMessage: 'fos_user.username.long'
                groups: ['Update', 'Register']