imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: stof.yml }
    - { resource: fos.yml }
    - { resource: jms.yml }
    - { resource: sms.yml }
    - { resource: knp.yml }
    - { resource: liip.yml }
    - { resource: vich.yml }
    - { resource: dunglas.yml }
    - { resource: fos_rest_mime_types.php }
    - { resource: jms_trans.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fa

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:
        csrf_protection:
            #TODO: activate dunglas csrf in production
            enabled: true
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_lifetime: 2592000
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
#            point: FunPro\GeoBundle\Doctrine\Type\PointType
#            linestring: FunPro\GeoBundle\Doctrine\Type\LineStringType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
        mapping_types:
            point: point
            linestring: linestring
            polygon: polygon
            geometry: geometry

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
#                point_str: FunPro\GeoBundle\Doctrine\ORM\Query\Functions\PointStr
#                distance: FunPro\GeoBundle\Doctrine\ORM\Query\Functions\Distance
                glength:         CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GLength
                linestring:      CrEOF\Spatial\ORM\Query\AST\Functions\MySql\LineString
                st_contains:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STContains
                contains:        CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Contains
                st_geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeomFromText
                point:           CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
                x:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\X
                y:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Y
            string_functions:
                UNIX_TIMESTAMP: DoctrineExtensions\Query\Mysql\UnixTimestamp
                GROUP_CONCAT:   DoctrineExtensions\Query\Mysql\GroupConcat
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
#            gedmo_translatable:
#                type: annotation
#                prefix: Gedmo\Translatable\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
#                alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
#                is_bundle: false
#            gedmo_translator:
#                type: annotation
#                prefix: Gedmo\Translator\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
#                alias: GedmoTranslator # (optional) it will default to the name set for the mapping
#                is_bundle: false
#            gedmo_loggable:
#                type: annotation
#                prefix: Gedmo\Loggable\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
#                alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
#                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # (optional) it will default to the name set for the mapping
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }