imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        crossed:
            type: fingers_crossed
            handler: deduplicated
            action_level: error
            excluded_404s: ["^/"]
            channels: ['!event', '!php', '!doctrine']
        deduplicated:
            type: deduplication
            handler: grouped
        grouped:
            type: whatfailuregroup
            members: [slack, file]
        file:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        slack:
            type: slack
            token: "xoxb-63535591344-yofIljobgRyy0FLMCGKvqwzZ"
            channel: 'server-logs'
            bot_name: FunPro_Logger
            include_extra: true