imports:
    - { resource: config.yml }
    - { resource: fixture.yml }
    - { resource: nelmio.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    session:
        cookie_domain: .%router.request_context.host%
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        crossed:
            type: fingers_crossed
            handler: grouped
            action_level: error
            excluded_404s: ["^/"]
        grouped:
            type: whatfailuregroup
            members: [deduplicated, file]
            channels: [!event]
        deduplicated:
            type: deduplication
            handler: slack
        file:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        slack:
            type: slack
            token: "xoxb-63535591344-yofIljobgRyy0FLMCGKvqwzZ"
            channel: 'server-logs'
            bot_name: FunPro_Logger
            include_extra: true
            level: ERROR
            channels: [!event]

#swiftmailer:
#    delivery_address: me@example.com

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Itaxi\Migrations
    table_name: migration_versions
    name: Application Migrations