imports:
    - { resource: config.yml }
    - { resource: fixture.yml }
    - { resource: nelmio.yml }

parameters:
    gcm.queue.process_in: 'kernel.response'
    gcm.queue.priority: 255

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    session:
        cookie_domain: .%router.request_context.host%
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        crossed:
            type: fingers_crossed
            handler: grouped
            action_level: error
            excluded_404s: ["^/"]
            channels: ['!event', '!php', '!doctrine']
        grouped:
            type: whatfailuregroup
            members: [deduplicated, file, rollbar]
        deduplicated:
            type: deduplication
            handler: slack
        file:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        slack:
            type: slack
            token: "xoxb-63535591344-yofIljobgRyy0FLMCGKvqwzZ"
            channel: 'server-logs'
            bot_name: FunPro_Logger
            include_extra: true
            level: INFO
        rollbar:
            type: rollbar
            token: 7333aebd4ce54050af1ac6cb89da1700
            level: INFO


#swiftmailer:
#    delivery_address: me@example.com

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Itaxi\Migrations
    table_name: migration_versions
    name: Application Migrations