dunglas_angular_csrf:
    token:
        id: angular
    header:
        name: X-XSRF-TOKEN
    cookie:
        name: XSRF-TOKEN
        expire: 0
        path:   /
        domain: "api.%router.request_context.host%"
        secure: false
        set_on:
            - { route: "api" }
            - { host: "api.%router.request_context.host%" }
    secure:
        - { route: "api", methods: [POST, PUT, DELETE, PATCH] }
        - { host: "api.%router.request_context.host%", methods: [POST, PUT, DELETE, PATCH] }