parameters:
    admin.email: ghanbari.daniel@gmail.com
    admin.username: ghanbari
    admin.password: 1
    test.passenger: false
    test.passenger.credentials: ~
    test.driver: true
    test.driver.credentials:
        3674240696: 1
        3674240697: 1
        3674240698: 1
        3674240699: 1
    test.agency: true
    test.agency.admin.credentials:
        agency1: 1
        agency2: 1
        agency3: 1