jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"
            CrEOF:
                namespace_prefix: "CrEOF\\Spatial\\PHP\\Types"
                path: "%kernel.root_dir%/serializer/CrEOF"