services:
    monolog.processor.introspection:
        class: Monolog\Processor\IntrospectionProcessor
        tags:
            - { name: monolog.processor }
    monolog.processor.web:
        class: Monolog\Processor\WebProcessor
        tags:
            - { name: monolog.processor, channel: app }
    monolog.processor.uid:
        class: Monolog\Processor\UidProcessor
        tags:
            - { name: monolog.processor }

#    not working in cpanel
#    monolog.processor.git:
#        class: Monolog\Processor\GitProcessor
#        tags:
#            - { name: monolog.processor, channel: app }