nelmio_api_doc:
    name: iTaxi
    default_sections_opened:  false
    request_listener:
        enabled:              false
    sandbox:
        enabled:              true
        accept_type:          application/json
        body_format:
            formats:
                - form
                - json
            default_format:   form
        request_format:
            formats:
                json:         application/json
            method:           accept_header
            default_format:   json
        authentication:
            delivery:           header
            name:               X-AUTH-TOKEN
            custom_endpoint:    false
        entity_to_choice:     true