fun_pro_ticket:
    resource: "@FunProTicketBundle/Resources/config/routing.yml"
    type:     rest

fun_pro_financial:
    resource: "@FunProFinancialBundle/Resources/config/routing.yml"
    type:     rest

fun_pro_admin_res:
    resource: "@FunProAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    options:
        expose: true
    type:     rest

fun_pro_service:
    resource: "@FunProServiceBundle/Resources/config/routing.yml"
    type:     rest

fun_pro_geo:
    resource: "@FunProGeoBundle/Resources/config/routing.yml"
    type:     rest
#
#fun_pro_engine:
#    resource: "@FunProEngineBundle/Resources/config/routing.yml"
#    type:     rest
#
#fun_pro_agent:
#    resource: "@FunProAgentBundle/Resources/config/routing.yml"
#    type:     rest
#
fun_pro_driver:
    resource: "@FunProDriverBundle/Resources/config/routing.yml"
    type:     rest

fun_pro_passenger:
    resource: "@FunProPassengerBundle/Resources/config/routing.yml"
    type:     rest

fun_pro_user:
    resource: "@FunProUserBundle/Resources/config/routing.yml"
    type:     rest

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"