security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SALESMAN:    ROLE_PASSENGER
        ROLE_OPERATOR:    ROLE_SALESMAN
        ROLE_ADMIN:       ROLE_OPERATOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        panel_login:
            pattern: ^/admin/login$
            form_login:
                login_path: fun_pro_admin_login
                check_path: fun_pro_admin_login_check
            anonymous: true
        panel:
            pattern: ^/admin
            form_login:
                login_path: fun_pro_admin_login
                check_path: fun_pro_admin_login_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: fun_pro_admin_logout
                target: fun_pro_admin_dashboard
        api:
            pattern: ^/
            host: api.%router.request_context.host%
            http_basic:
                provider: fos_userbundle
            guard:
                authenticators:
                    - fun_pro_engine.token_authenticator
            form_login:
                provider: fos_userbundle
                require_previous_session: false
            logout:       true
            anonymous: true
        main:
            pattern: ^/
            http_basic:
                provider: fos_userbundle
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/passenger$, methods: [POST], host: "api.%router.request_context.host%", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/passenger/confirm$, methods: [POST], host: "api.%router.request_context.host%", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/passenger, host: "api.%router.request_context.host%", role: ROLE_PASSENGER }
        - { path: ^/driver, host: "api.%router.request_context.host%", role: ROLE_DRIVER }