security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SALESMAN:    ROLE_PASSENGER
        ROLE_OPERATOR:    ROLE_SALESMAN
        ROLE_ADMIN:       ROLE_OPERATOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        panel:
            pattern: ^/admin
            form_login:
                login_path: fun_pro_admin_login
                check_path: fun_pro_admin_login_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: fun_pro_admin_logout
                target: fun_pro_admin_dashboard
            anonymous:    true
        api_passenger:
            pattern: ^/passenger
            host: api.%router.request_context.host%
            guard:
                authenticators:
                    - fun_pro_engine.token_authenticator
            stateless: true
        api:
            pattern: ^/
            host: api.%router.request_context.host%
            http_basic:
                provider: fos_userbundle
            form_login:
                provider: fos_userbundle
                require_previous_session: false
            logout:       false
        main:
            pattern: ^/
            http_basic:
                provider: fos_userbundle
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }