security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api_passenger:
            pattern: ^/passenger
            host: api.%router.request_context.host%
            guard:
                authenticators:
                    - fun_pro_engine.token_authenticator
            logout:       false
            anonymous:    true
            stateless: true
        api:
            pattern: ^/
            host: api.%router.request_context.host%
            http_basic:
                provider: fos_userbundle
            form_login:
                provider: fos_userbundle
                require_previous_session: false
            logout:       false
            anonymous:    true
        main:
            pattern: ^/
            http_basic:
                provider: fos_userbundle
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }