security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_OPERATOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        panel_login:
            pattern: ^/login$
            host: %admin.panel.host%
            form_login:
                login_path: fun_pro_admin_login
                check_path: fun_pro_admin_login_check
            anonymous: true
        panel:
            pattern: ^/
            host: %admin.panel.host%
            form_login:
                login_path: fun_pro_admin_login
                check_path: fun_pro_admin_login_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: fun_pro_admin_logout
                target: fun_pro_admin_dashboard
        api_create_device:
            pattern: ^/(doc|passenger$|passenger/confirm|device$|login_check|config/global)
            host: api.%router.request_context.host%
            http_basic:
                provider: fos_userbundle
            guard:
                authenticators:
                    - fun_pro_engine.user_token_authenticator
            form_login:
                provider: fos_userbundle
                require_previous_session: false
            logout:       true
            anonymous: true
        api:
            pattern: ^/
            host: api.%router.request_context.host%
            guard:
                authenticators:
                    - fun_pro_engine.device_token_authenticator
            stateless: true
            anonymous: false
        main:
            pattern: ^/
            http_basic:
                provider: fos_userbundle
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, host: %admin.panel.host%, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, host: %admin.panel.host%, role: ROLE_OPERATOR }
        - { path: ^/passenger$, methods: [POST], host: "api.%router.request_context.host%", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/passenger/confirm$, methods: [POST], host: "api.%router.request_context.host%", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/passenger, role: ROLE_PASSENGER }
        - { path: ^/driver, role: ROLE_DRIVER }