imports:
    - { resource: "@FunProUserBundle/Resources/config/services.yml" }
    - { resource: "@FunProPassengerBundle/Resources/config/services.yml" }
    - { resource: "@FunProDriverBundle/Resources/config/services.yml" }
    - { resource: "@FunProAgentBundle/Resources/config/services.yml" }
    - { resource: "@FunProEngineBundle/Resources/config/services.yml" }
    - { resource: "@FunProGeoBundle/Resources/config/services.yml" }
    - { resource: "@FunProServiceBundle/Resources/config/services.yml" }
    - { resource: "@FunProAdminBundle/Resources/config/services.yml" }
    - { resource: "@FunProFinancialBundle/Resources/config/services.yml" }
    - { resource: "@FunProTicketBundle/Resources/config/services.yml" }
    - { resource: "@FunProHomeBundle/Resources/config/services.yml" }
    - { resource: monolog.yml }