k_phoen_sms_sender:
    pool:         memory
    http_adapter: "%sms_adapter%"
    providers:    ["%sms_provider%"]
    factories: ['%kernel.root_dir%/config/sms_provider_factories.xml']

    sms_ir:
        user: "%sms_ir.user%"
        pass: "%sms_ir.pass%"
        from: "%sms_ir.from%"
        international_prefix: '+98'

    nik_sms:
        user: "%nik_sms.user%"
        pass: "%nik_sms.pass%"
        from: "%nik_sms.from%"
        international_prefix: '+98'

    niaz_pardaz:
        user: "%niaz_pardaz.user%"
        pass: "%niaz_pardaz.pass%"
        from: "%niaz_pardaz.from%"
        international_prefix: '+98'