vich_uploader:
    db_driver: orm

    mappings:
        car_image:
            uri_prefix:         /images/cars
            upload_destination: "%kernel.root_dir%/../web/images/cars"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        user_avatar:
            uri_prefix:         /images/avatars
            upload_destination: "%kernel.root_dir%/../web/images/avatars"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true