FunPro\UserBundle\Entity\User:
    properties:
        username:
            - Length:
                min: 2
                max: 255
                minMessage: fos_user.username.short
                maxMessage: fos_user.username.long
                groups: [Register, Profile]
        plainPassword:
            - NotBlank:
                groups: [Register]
                message: fos_user.password.blank
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [Register, Profile]
        email:
            - Length:
                min: 2
                max: 255
                maxMessage: fos_user.email.long
                groups: [Register, Profile]
            - Email:
                message: fos_user.email.invalid
                groups: [Register, Profile]