fun_pro_passenger_api:
    resource: FunPro\PassengerBundle\Controller\PassengerController
    type: rest
    options:
        version: true
fun_pro_passenger_api_profile:
    resource: "@FunProPassengerBundle/Controller/ProfileController.php"
    type: rest
    parent: fun_pro_passenger_api