fun_pro_passenger_api:
    resource: FunPro\PassengerBundle\Controller\PassengerController
    type: rest
    options:
        version: true

fun_pro_passenger_device_api:
    resource: FunPro\PassengerBundle\Controller\DeviceController
    parent: fun_pro_passenger_api
    type: rest
    options:
        version: true