fun_pro_service_wakeful_api:
    resource: FunPro\ServiceBundle\Controller\WakefulController
    type: rest

fun_pro_service_api:
    resource: FunPro\ServiceBundle\Controller\ServiceController
    type: rest