services:
    fun_pro_service.service_log_subscriber:
        class: FunPro\ServiceBundle\Event\ServiceSubscriber
        arguments: ["@doctrine", "@logger", "@jms_serializer"]
        tags:
            - { name: kernel.event_subscriber }

    fun_pro_service.service_notification_subscriber:
        class: FunPro\ServiceBundle\Event\ServiceNotificationListener
        arguments: ["@fun_pro_engine.gcm", "@doctrine", "@logger", "@serializer", "@=container.getParameterBag()"]
        tags:
            - { name: kernel.event_subscriber }