services:
    fun_pro_service.service_log_subscriber:
        class: FunPro\ServiceBundle\Event\ServiceSubscriber
        arguments: ["@doctrine", "@logger", "@jms_serializer"]
        tags:
            - { name: kernel.event_subscriber }
