fun_pro_driver_report_api:
    resource: "@FunProDriverBundle/Controller/ReportController.php"
    type: rest
    prefix: /driver

fun_pro_driver_profile_api:
    resource: "@FunProDriverBundle/Controller/ProfileController.php"
    type: rest
    prefix: /driver