services:
    fun_pro_driver.car_log_subscriber:
        class: FunPro\DriverBundle\EventListener\CarLogSubscriber
        arguments: ["@doctrine"]
        tags:
            - { name: kernel.event_subscriber }
